#!/bin/bash

# Add all files
# Commit with the date and autogenerated message
# Push

LOG_PATH="${HOME}/Documents/logs"

message="Autogenerated commit: `date`"

cd "${LOG_PATH}"
git add -A
git diff --cached --exit-code
if [ ! $? -eq 0 ] ; then
  git commit -m "${message}"
  git push --all
fi
